[package]
name = "pumpkin-lib"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
thiserror = "1.0.39"
log = "0.4.17"
bitfield = "0.14.0"
enumset = "1.1.2"
slice-dst = "1.5.1"
fnv = "1.0.3"

[dev-dependencies]
env_logger = "0.10.0"
