rcpsp_smaller_Bl2520 = ["models/linear/rcpsp_smaller_Bl2520.fzn"]
rcpsp_smaller_J90_1_1 = ["models/linear/rcpsp_smaller_J90_1_1.fzn"]
rcpsp_smaller_J30_1_2 = ["models/linear/rcpsp_smaller_J30_1_2.fzn"]
rcpsp_smaller_J90_1_2 = ["models/linear/rcpsp_smaller_J90_1_2.fzn"]
rcpsp_smaller_J60_1_2 = ["models/linear/rcpsp_smaller_J60_1_2.fzn"]
rcpsp_smaller_st103_8 = ["models/linear/rcpsp_smaller_st103_8.fzn"]
rcpsp_smaller_j304_3 = ["models/linear/rcpsp_smaller_j304_3.fzn"]
rcpsp_smaller_J90_1_9 = ["models/linear/rcpsp_smaller_J90_1_9.fzn"]
rcpsp_smaller_j304_2 = ["models/linear/rcpsp_smaller_j304_2.fzn"]
rcpsp_smaller_j304_1 = ["models/linear/rcpsp_smaller_j304_1.fzn"]
rcpsp_smaller_st103_9 = ["models/linear/rcpsp_smaller_st103_9.fzn"]
rcpsp_smaller_J90_1_10 = ["models/linear/rcpsp_smaller_J90_1_10.fzn"]
rcpsp_smaller_pack051 = ["models/linear/rcpsp_smaller_pack051.fzn"]
rcpsp_smaller_st103_14 = ["models/linear/rcpsp_smaller_st103_14.fzn"]
rcpsp_smaller_pack050 = ["models/linear/rcpsp_smaller_pack050.fzn"]
rcpsp_smaller_J30_1_3 = ["models/linear/rcpsp_smaller_J30_1_3.fzn"]
rcpsp_smaller_pack033 = ["models/linear/rcpsp_smaller_pack033.fzn"]
rcpsp_smaller_st103_44 = ["models/linear/rcpsp_smaller_st103_44.fzn"]
rcpsp_smaller_Bl2519 = ["models/linear/rcpsp_smaller_Bl2519.fzn"]
rcpsp_smaller_pack032 = ["models/linear/rcpsp_smaller_pack032.fzn"]
rcpsp_smaller_la36_x2 = ["models/linear/rcpsp_smaller_la36_x2.fzn"]
rcpsp_smaller_la35_x3 = ["models/linear/rcpsp_smaller_la35_x3.fzn"]
rcpsp_smaller_J60_1_1 = ["models/linear/rcpsp_smaller_J60_1_1.fzn"]
rcpsp_smaller_J30_1_1 = ["models/linear/rcpsp_smaller_J30_1_1.fzn"]
