rcpsp_small_pack024 = ["models/rcpsp/rcpsp_small_pack024.fzn"]
rcpsp_pack024 = ["models/rcpsp/rcpsp_pack024.fzn"]
rcpsp_J120_35_5 = ["models/rcpsp/rcpsp_J120_35_5.fzn"]
rcpsp_small_08 = ["models/rcpsp/rcpsp_small_08.fzn"]
rcpsp_08 = ["models/rcpsp/rcpsp_08.fzn"]
rcpsp_J120_34_7 = ["models/rcpsp/rcpsp_J120_34_7.fzn"]
rcpsp_J90_21_3 = ["models/rcpsp/rcpsp_J90_21_3.fzn"]
rcpsp_st103_14 = ["models/rcpsp/rcpsp_st103_14.fzn"]
rcpsp_st103_44 = ["models/rcpsp/rcpsp_st103_44.fzn"]
rcpsp_J60_46_4 = ["models/rcpsp/rcpsp_J60_46_4.fzn"]
rcpsp_small_J30_29_3 = ["models/rcpsp/rcpsp_small_J30_29_3.fzn"]
rcpsp_J90_42_2 = ["models/rcpsp/rcpsp_J90_42_2.fzn"]
rcpsp_J90_37_1 = ["models/rcpsp/rcpsp_J90_37_1.fzn"]
rcpsp_J120_28_2 = ["models/rcpsp/rcpsp_J120_28_2.fzn"]
rcpsp_J90_26_2 = ["models/rcpsp/rcpsp_J90_26_2.fzn"]
rcpsp_J120_20_8 = ["models/rcpsp/rcpsp_J120_20_8.fzn"]
rcpsp_small_J90_37_1 = ["models/rcpsp/rcpsp_small_J90_37_1.fzn"]
rcpsp_J60_41_9 = ["models/rcpsp/rcpsp_J60_41_9.fzn"]
rcpsp_pack026 = ["models/rcpsp/rcpsp_pack026.fzn"]
rcpsp_pack008 = ["models/rcpsp/rcpsp_pack008.fzn"]
rcpsp_J120_21_2 = ["models/rcpsp/rcpsp_J120_21_2.fzn"]
rcpsp_small_st103_14 = ["models/rcpsp/rcpsp_small_st103_14.fzn"]
rcpsp_J30_29_3 = ["models/rcpsp/rcpsp_J30_29_3.fzn"]
rcpsp_pack045 = ["models/rcpsp/rcpsp_pack045.fzn"]
