[package]
name = "drcp-format"
version = "0.3.0"
description = "Parse and write DRCP and literal definition files."
license.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
nom = "7.1.3"
thiserror = "1.0.59"
